# Generated by Django 3.2.9 on 2021-12-07 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('related_person_name', models.CharField(max_length=100)),
                ('monthly_reminder', models.BooleanField(default=False)),
                ('yearly_reminder', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding Anniversary', 'Wedding Anniversary'), ('Relationship Anniversary', 'Relationship Anniversary'), ('Bill Payment', 'Bill Payment'), ('Other', 'Other')], default='Birthday', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='How would you like to be called', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding Anniversary', 'Wedding Anniversary'), ('Relationship Anniversary', 'Relationship Anniversary'), ('Bill Payment', 'Bill Payment'), ('Other', 'Other')], default='Birthday', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_datetime', models.DateTimeField(auto_now_add=True)),
                ('successfully_sent', models.BooleanField(default=False)),
                ('reminder_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dates.reminder')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('message_type', models.CharField(choices=[('Whatsapp', 'Whatsapp')], default='Whatsapp', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
