# Generated by Django 3.2.9 on 2021-11-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='event_type',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding Anniversary', 'Wedding Anniversary'), ('Relationship Anniversary', 'Relationship Anniversary'), ('Bill Payment', 'Bill Payment'), ('Other', 'Other')], default='Birthday', max_length=30),
        ),
    ]
