# Generated by Django 3.2.9 on 2021-11-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0002_alter_reminder_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='yearly_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
