# Generated by Django 3.2.9 on 2021-12-17 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_alter_reminder_yearly_reminder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['date']},
        ),
    ]
