# Generated by Django 3.2.9 on 2021-12-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0004_alter_reminder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['date__day']},
        ),
    ]
